<script>
  import { Check, Zap, Code, Clock, GitCommit } from 'lucide-svelte';
  
  const stats = [
    { icon: Zap, label: 'Built by', value: 'FORGE v0.0.1' },
    { icon: Code, label: 'Files', value: '11 source files' },
    { icon: Clock, label: 'Time', value: '~15 minutes' },
    { icon: GitCommit, label: 'Commit', value: 'a62ed69' },
  ];
</script>

<section id="showcase" class="py-24 px-6 bg-gradient-to-b from-background via-[#0d0d1a] to-background">
  <div class="max-w-5xl mx-auto">
    <!-- Badge -->
    <div class="text-center mb-12">
      <div class="inline-flex items-center gap-2 px-4 py-1.5 bg-accent-indigo/10 border border-accent-indigo/20 rounded-full text-accent-indigo text-sm font-mono mb-6">
        <Check class="w-4 h-4" />
        Real Example
      </div>
      <h2 class="text-4xl md:text-5xl font-bold mb-4">
        This Website Was Built by <span class="text-accent-indigo">FORGE</span>
      </h2>
      <p class="text-xl text-white/50 max-w-2xl mx-auto">
        The page you're looking at right now was generated by FORGE from a single prompt.
        No human wrote a line of HTML, CSS, or JS. This is what FORGE ships.
      </p>
    </div>

    <!-- Stats grid -->
    <div class="grid grid-cols-2 md:grid-cols-4 gap-4 mb-16">
      {#each stats as stat}
        <div class="bg-surface border border-white/5 rounded-xl p-6 text-center hover:border-accent-indigo/30 transition-all group">
          <div class="inline-flex items-center justify-center w-10 h-10 bg-accent-indigo/10 rounded-lg mb-3 group-hover:scale-110 transition-transform">
            <svelte:component this={stat.icon} class="w-5 h-5 text-accent-indigo" />
          </div>
          <div class="text-2xl font-bold mb-1 text-white">{stat.value}</div>
          <div class="text-sm text-white/40">{stat.label}</div>
        </div>
      {/each}
    </div>

    <!-- The prompt -->
    <div class="bg-[#0a0a0f] border border-white/10 rounded-2xl overflow-hidden shadow-2xl">
      <div class="bg-white/5 px-5 py-3 flex items-center gap-2 border-b border-white/5">
        <span class="w-3 h-3 rounded-full bg-red-500/60"></span>
        <span class="w-3 h-3 rounded-full bg-yellow-500/60"></span>
        <span class="w-3 h-3 rounded-full bg-green-500/60"></span>
        <span class="ml-3 text-sm text-white/30 font-mono">~/Desktop/forge — forge-cli</span>
      </div>
      <div class="p-5 font-mono text-sm text-white/60 leading-relaxed overflow-x-auto max-h-64 overflow-y-auto">
        <span class="text-accent-green">▸</span> <span class="text-white/80">Build a modern, single-page landing website for FORGE-CLI — a multi-model terminal AI coding agent...</span>
        <br><br>
        <span class="text-accent-cyan">◈</span> <span class="text-white/40">list_files</span> <span class="text-white/20">path=.</span>
        <br>
        <span class="text-accent-cyan">◈</span> <span class="text-white/40">read_file</span> <span class="text-white/20">path=README.md</span>
        <br>
        <span class="text-accent-cyan">◈</span> <span class="text-white/40">read_file</span> <span class="text-white/20">path=CHANGELOG.md</span>
        <br>
        <span class="text-accent-cyan">◈</span> <span class="text-white/40">write_file</span> <span class="text-white/20">site/package.json</span> <span class="text-accent-green">✓</span>
        <br>
        <span class="text-accent-cyan">◈</span> <span class="text-white/40">write_file</span> <span class="text-white/20">site/astro.config.mjs</span> <span class="text-accent-green">✓</span>
        <br>
        <span class="text-accent-cyan">◈</span> <span class="text-white/40">write_file</span> <span class="text-white/20">site/src/components/Hero.astro</span> <span class="text-accent-green">✓</span>
        <br>
        <span class="text-accent-cyan">◈</span> <span class="text-white/40">write_file</span> <span class="text-white/20">site/src/components/Terminal.svelte</span> <span class="text-accent-green">✓</span>
        <br>
        <span class="text-white/20">... 11 files created, 2 deps installed, 1 build error auto-fixed</span>
        <br><br>
        <span class="text-accent-green">◆</span> <span class="text-accent-green font-bold">REASONING</span> <span class="text-white/80">FORGE built the entire site. 11 source files. Compiled clean. Ready for production.</span>
        <br>
        <span class="text-accent-green">DONE</span> <span class="text-white/60">Task complete.</span>
      </div>
    </div>

    <!-- Bottom CTA -->
    <div class="text-center mt-12">
      <a 
        href="https://github.com/pratikacharya1234/forge/commit/a62ed69533f7ee2189d99bdc19b50339384df17e" 
        target="_blank"
        class="inline-flex items-center gap-2 px-6 py-3 bg-accent-indigo/10 hover:bg-accent-indigo/20 border border-accent-indigo/30 rounded-xl text-accent-indigo font-bold transition-all text-sm"
      >
        <GitCommit class="w-4 h-4" />
        View the commit that built this site →
      </a>
      <p class="mt-4 text-sm text-white/30">
        Same prompt works with Claude Code, Cursor, or Copilot. FORGE just does it for free.
      </p>
    </div>
  </div>
</section>
